### ISSUE TITLE
Strings in NeXus

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/NIAC#10]
An issue (yes, another one) has come up regarding strings in NeXus. HDF5 now allows to write variable length strings. Some popular software, like h5py, actually uses this feature. The problem is that the variable length strings API in HDF5 is not very well though out. Thus the existence of both normal strings and variable length strings in a NeXus file imposes a burden on reading code which does not use the NeXus API. The burden is that you have to check first if this a variable length string or not and then proceed to read the data differently. 

I think we need to discuss this and decide if we standardize on normal strings or if we allow both forms of strings and impose the additional burden for reading string data on users.

**Comment by mkoennecke** [comment]
[nxvutil.txt](https://github.com/nexusformat/NIAC/files/361387/nxvutil.txt)

This file is an example from cnxvalidate for the loops you have to jump in order to read both normal and variable length strings. And this is a simplified version which does not take string arrays into account.

**Comment by zjttoefs** [comment]
We had that discussion, but did make a formal decision. If I recall correctly.

As you say h5py uses variable lengths strings by default, not allowing that would be quite irritating. NAPI uses fixed length strings by default. So not allowing that would break backward compatibility. There are more examples out there for both sides.
Therefore I think accepting both types of strings should be a requirement for software claiming NeXus compliance.

Since all is not a problem for h5py users and even NAPI reads both types to some extend, we can blame the situation on the API people or the HDF group.

**Comment by mkoennecke** [comment]
I remember the discussion but I do not remember voting on it. Shall we put that then on as a quick decision item for the NIAC or close it right away?

**Comment by zjttoefs** [comment]
A formal NIAC vote is a good idea!

**Comment by zjttoefs** [comment]
That can be quickly raise at NIAC without much preparation.
