### ISSUE TITLE
Discuss/ratify NXreflections

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/NIAC#15]
This is the NeXus extension proposed and developed by James Parkhurst at Diamond for recording integrated reflection intensities after data reduction.  The extension is already needed by scientists doing serial crystallography to decrease number of files in directories produced by processing thousands of individual stills at once.

**Comment by prjemian** [comment]
The name is very general while the application is specific.  Can this be renamed to indicate more precisely its scope?

Can you provide here a repository to consider for a pull request to NeXus definitions?  Documentation?

**Comment by phyy-nx** [comment]
Hi Pete, the name is negotiable, for sure.  I prefer NXreflections, for example.

Regarding a pull request, you are referring to this repository, I believe? https://github.com/nexusformat/definitions/tree/master/applications. James provided an application xml which I can set up as a pull request to that repository. I also have an example nexus file I created using the dials.export tool that includes an NXdiffraction entry.  I can provide this if it's helpful.

My intent is to synthesize James's notes and my understanding before the NIAC in the form of a small talk.
-Aaron

**Comment by prjemian** [comment]
**NXreflections** seems about right for what is described, and leaves **NXdiffraction** available should a use case so broad be presented.

Best to fork the https://github.com/nexusformat/definitions repository to your GitHub account, then add ``contributed_definitions/NXreflections.nxdl.xml``.  This will have the requisite structure for a successful pull request.

Before the NIAC ratifies a new NXDL file, it can reside in the contributed definitions directory.  Once ratified, it will be moved (by someone like me) into the appropriate location (``applications `` for this NXDL).  The nexusformat/definitions repository is not the right place for example data files.  We try to keep them out since they just increase the size of the repository download.  (Even if deleted, they still remain in the database for possible recovery.)  NeXus has an example data repository (https://github.com/nexusformat/exampledata) in which such files could be placed.  You could fork that repo, add the file in a subdirectory, then submit a pull request.  Or, you could send to me (or anyone else with write access to that repo) and to have it added (shortcuts the repo fork & PR process).

**Comment by phyy-nx** [comment]
Perfect.  Thanks Pete.

**Comment by phyy-nx** [comment]
Ok, both pull requests are made, one in nexusformat/definitions and the other in nexusformat/exampledata.

**Comment by prjemian** [comment]
Thanks.  A syntax review of the proposed NXDL has been posted, requesting some changes.

**Comment by prjemian** [comment]
Note: 
* NXDL: https://github.com/nexusformat/definitions/pull/485
* data: https://github.com/nexusformat/exampledata/pull/4

**Comment by prjemian** [comment]
* NXDL now added to contributed definitions
* documentation: http://download.nexusformat.org/doc/html/classes/contributed_definitions/NXreflections.html

**Comment by zjttoefs** [comment]
Ratified.
