### ISSUE TITLE
[NIAC 2018 Discussion] Discuss HDF5XMP metadata

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#32]
The code uploaded to the hdf5xmp repository provides a framework to add metadata (and thumbnails) to HDF5 files (or in sidecar .xmp files) and a set of plugins to provide included thumbnails to file browsers. Does anybody foresee any issues with the approach used? Does the NIAC support furthering this implementation?

**Comment by vasole** [comment]
I will need a description of what is actually done because I have taken one of the example files:

https://github.com/nexusformat/hdf5xmp/blob/master/examples/PLV_160502001.hdf5

and I have seen it contains a thumb dataset.

At that point I see nothing that could not been achieved by the NXnote class:

http://download.nexusformat.org/doc/html/classes/base_classes/NXnote.html#nxnote

**Comment by vasole** [comment]
As a side note, your NX_class attributes contain arrays of bytes, no single strings, no utf-8.

**Comment by benajamin** [comment]
I think you missed the point here. That particular file contains an image from a visible light microscope as the core data. The thumbnail is written into the HDF5 userblock so that it can be read without needing the HDF5 library.
I'll look into how the attributes are being written - it is with h5py in this case.

**Comment by mkoennecke** [comment]
Ben Watts at PSI implemented this. The thumbnail is placed in a user block before the HDF5 content. Plugins for most file browsers exist which can display this information. This means when you browse a directory full of NeXus files, you can see thumbnails of your data. If the thumbnails have been generated and written. Some python code to do this also exists.

The NIAC thanks Ben Watts and PSI for implementing this
