### ISSUE TITLE
[NIAC2020] Discuss future of python in NeXus API language bindings

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#43]
Proposed by @rayosborn

**Comment by prjemian** [comment]
At [the 2020-12-08 telco](https://www.nexusformat.org/Telco_20201208.html), we discussed this briefly.  We'll leave the existing python binding in the code repository but not include that in new releases.  Closing this issue here since we have decisions on what to do with both code and definitions repositories.
